window.MATHBRO_PAGES=[
  {"title":"פרק 1: סדר פעולות החשבון · מתמטיקה לחרדים","file":"learn/seder_peulot.html","chapter":1,"group":"יסודות","level":"בסיס"},
  {"title":"פרק 2: מספרים שליליים · מתמטיקה לחרדים","file":"learn/shliliyim.html","chapter":2,"group":"יסודות","level":"בסיס"},
  {"title":"פרק 3: שברים פשוטים · מתמטיקה לחרדים","file":"learn/shvarim.html","chapter":3,"group":"יסודות","level":"בסיס"},
  {"title":"פרק 4: אחוזים · מתמטיקה לחרדים","file":"learn/achuzim.html","chapter":4,"group":"יסודות","level":"בסיס"},
  {"title":"פרק 5: חזקות · מתמטיקה לחרדים","file":"learn/chazakot.html","chapter":5,"group":"יסודות","level":"בסיס"},
  {"title":"פרק 6: שורשים · מתמטיקה לחרדים","file":"learn/shorashim.html","chapter":6,"group":"יסודות","level":"בסיס"},
  {"title":"פרק 7: חזקה שלילית · מתמטיקה לחרדים","file":"learn/chazaka_shlili.html","chapter":7,"group":"יסודות","level":"מתקדם"},
  {"title":"פרק 8: כינוס איברים · מתמטיקה לחרדים","file":"learn/kinus_evarim.html","chapter":8,"group":"אלגברה","level":"בסיס"},
  {"title":"פרק 9: פתיחת סוגריים · מתמטיקה לחרדים","file":"learn/kefel_sograyim.html","chapter":9,"group":"אלגברה","level":"בסיס"},
  {"title":"פרק 10: כפל מקוצר · מתמטיקה לחרדים","file":"learn/kefel_mekutzar.html","chapter":10,"group":"אלגברה","level":"מתקדם"},
  {"title":"פרק 11: נוסחאות · מתמטיקה לחרדים","file":"learn/noschaot.html","chapter":11,"group":"אלגברה","level":"כלי עבודה"},
  {"title":"פרק 12: משוואות · מתמטיקה לחרדים","file":"learn/mishvaot.html","chapter":12,"group":"משוואות","level":"בסיס"},
  {"title":"פרק 13: מערכת משוואות · מתמטיקה לחרדים","file":"learn/maarechet.html","chapter":13,"group":"משוואות","level":"מתקדם"},
  {"title":"פרק 14: משוואה ריבועית · מתמטיקה לחרדים","file":"learn/mishvaa_ribuit.html","chapter":14,"group":"משוואות","level":"מתקדם"},
  {"title":"פרק 15: בעיות מילוליות · מתמטיקה לחרדים","file":"learn/beayot_miluliyot.html","chapter":15,"group":"משוואות","level":"תרגול"},
  {"title":"פרק 16: פונקציות · מתמטיקה לחרדים","file":"learn/funktziot.html","chapter":16,"group":"גרפים","level":"בסיס"},
  {"title":"פרק 17: גיאומטריה אנליטית · מתמטיקה לחרדים","file":"learn/geo_analytit.html","chapter":17,"group":"גרפים","level":"מתקדם"},
  {"title":"פרק 18: משולשים · מתמטיקה לחרדים","file":"learn/meshulashim.html","chapter":18,"group":"גיאומטריה","level":"בסיס"},
  {"title":"פרק 19: טריגונומטריה · מתמטיקה לחרדים","file":"learn/trigo.html","chapter":19,"group":"גיאומטריה","level":"מתקדם"},
  {"title":"פרק 20: תרגול פרק ב · מתמטיקה לחרדים","file":"learn/tirgul_perek_b.html","chapter":20,"group":"תרגול","level":"אימון"},
  {"title":"פרק 21: סיפורי דרך לפתרון · מתמטיקה לחרדים","file":"learn/sippurim.html","chapter":21,"group":"תרגול","level":"חשיבה"},
  {"title":"פרק 22: טיפים למבחן · מתמטיקה לחרדים","file":"learn/tipim.html","chapter":22,"group":"מבחנים","level":"הכנה"},
  {"title":"פרק 23: מבחני סיכום · מתמטיקה לחרדים","file":"learn/mivchan_sikum.html","chapter":23,"group":"מבחנים","level":"סיכום"},
  {"title":"פרק 24: שימוש נכון במחשבון Casio · מתמטיקה לחרדים","file":"calculator/casio-tutorial.html","chapter":24,"group":"מחשבון","level":"כלי עבודה"}
];
